server:
  port: 8088

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      topics:
        exam: exam
        exam2: exam2
        exam3: exam3
        exam4: exam4
        error-test-topic: error-test-topic
        record-test: record-test

