server:
  port: 8081

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: test-group
    topics:
      exam: exam
      exam2: exam2
      exam3: exam3
      exam4: exam4
      dead-letter: dead-letter
      error-test-topic: error-test-topic
      record-test: record-test
      record-test2: record-test2
      record-test3: record-test3
    producer:
      bootstrap-servers: localhost:29092
    backoff:
      interval: 3000
      max_failure: 3

#logging:
#  level:
#    ROOT: DEBUG
