server:
  port: 8081

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: test-group
    topics:
      exam: exam
      exam2: exam2
      exam3: exam3
      exam4: exam4
      dead-letter: dead-letter
      error-test-topic: error-test-topic
